
minify_out ?= "build/minified_main.lua"
cc_out ?= "build/cc_main.lua"

modules := radar cache targetter

minify_command := lua54.exe "./lua-minify/minify.lua" minify $(cc_out)
combining_command := bun .\combine_lua_files.js -m main.lua -o $(cc_out) -n $(modules)


clippath ?= "clip.exe"
build ?= "SCI"
verbose ?= true

.DEFAULT_GOAL = clip

clip: minify
	$(minify_command) | $(clippath)
minify: combining
	$(minify_command) > $(minify_out)
combining:
	$(combining_command)